pyimage:
  gaussian_head:
    num_surfaces: 1
    gaussians_per_pixel: 1
    opacity_mapping:
      initial: 0.0
      final: 0.0
      warm_up: 1
    wo_pgs: false
    wo_pgs_res: true
    gh_mvs_scale_factor: 1
    unify_gh_res: true
    wo_disp_dens_refine: true
    wo_fibo_gs: false
    wo_sh_res: false
    wo_feat: false
    use_latlon_embedding: true
    latlon_embedding_freqs: 2
    use_latitude_aware_conv: true
    latitude_aware_conv_freqs: 2
    latitude_aware_dilations: [1, 2, 4]
    fibo_mlp_layers: 1
    gh_cnn_layers: 2
    patchs_height: 1
    patchs_width: 1
    gaussian_adapter:
      gaussian_scale_min: 0.5
      gaussian_scale_max: 15.0
      sh_degree: 4
      use_jacobian_aware_scale: true
      use_jacobian_aware_basis: true
      return_world_space_rotations: true
      jacobian_scale_multiplier: 0.1
      jacobian_scale_radial_factor: 0.5
    deferred_blend: true
  decoder:
    name: splatting_cuda
    view_batch: 20
    super_sampling: 1.
  mse:
    weight: 1.0
  lpips:
    weight: 0.05
    apply_after_step: 0
  gamma: 0.9
